Class {
	#name : #GtWorldSanityCheck,
	#superclass : #Object,
	#category : 'GToolkit-World-Examples'
}

{ #category : #accessing }
GtWorldSanityCheck class >> checkImage: aFileReference [
	"Run the receiver in the supplied image using the current VM."
	| proc timedOut pharoDebug |

	pharoDebug := Smalltalk logFileName asFileReference.
	self assert: pharoDebug exists not.
	
	proc := self createCheckProcessForImageFile: aFileReference.
	proc runAndSignal.
	
	timedOut := proc waitTimeoutMilliseconds: 5 * 60 * 1000.
	timedOut ifTrue:
		[ self error: 'Check image process didn''t complete in time' ].
	
	proc isSuccess ifFalse:
		[ self error: 'Check image process didn''t succeed' ].
	(proc stdout includesSubstring: 'GtWorldSanityCheck pass') ifFalse:
		[ self error: 'Check image process didn''t pass' ].
		
	pharoDebug exists ifTrue:
		[ self error: 'PharoDebug log file present after running checks' ].
]

{ #category : #accessing }
GtWorldSanityCheck class >> checkOnDiskImage [
	"Confirm that the on-disk image opens.
	The image must be able to be run interactively."

	self checkImage: Smalltalk imageFile resolve
]

{ #category : #accessing }
GtWorldSanityCheck class >> createCheckProcessForImageFile: aFileReference [
	| vm arguments |
	vm := LanguageLinkSettings pharoDefaultSettings serverExecutable.
	arguments := {'--interactive'.
			aFileReference fullName.
			'clap'.
			'eval'.
			self name asString.
			'new'.
			'checkImage'.
			'--detachChanges'.
			'--epiceaMemoryStore'.
			'--noLepiterReload'.
			'--noGtImageUpdate'}.
	^ GtSubprocessWithInMemoryOutput
			command: vm fullName
			arguments: arguments
]

{ #category : #checking }
GtWorldSanityCheck >> checkImage [

	[ self runChecks.
	Stdio stdout lf; << 'GtWorldSanityCheck pass'; lf ]
		on: Exception
		do: [ :ex |
			Stdio stdout 
				lf; 
				<< 'GtWorldSanityCheck failed: ';
				<< ex printString;
				lf.
			Smalltalk exit: 1 ].
	Smalltalk exit: 0.
]

{ #category : #checking }
GtWorldSanityCheck >> runChecks [
	| gtWorld |

	self waitForWorldToInitialize.
	
	gtWorld := GtWorld allOpenWorlds anyOne.
	self assert: gtWorld isOpened.
	
	self runChecksForWorld: gtWorld.
]

{ #category : #checking }
GtWorldSanityCheck >> runChecksForWorld: aGtWorld [
	self runScreenshotChecksForWorld: aGtWorld.
]

{ #category : #checking }
GtWorldSanityCheck >> runScreenshotChecksForWorld: aGtWorld [
	| image screenshot |
	
	screenshot := aGtWorld root exportAsPNG.
	self assert: screenshot exists.
	
	image := ImageReadWriter gtFormFromFileReference:  screenshot.
	self assert: (image width between: 600 and: 2000).
	self assert: (image height between: 400 and: 2000).
	
	^ screenshot
]

{ #category : #utils }
GtWorldSanityCheck >> waitForWorldToInitialize [
	"For now we use a fix delay"
	15 seconds wait.
]
